#!/bin/bash

SPIKE_DIR=$PWD/riscv-isa-sim

SPIKE_BUILD_DIR=$SPIKE_DIR/build
SPIKE_INSTALL_DIR=$SPIKE_DIR/install
SPIKE_BIN_DIR=$SPIKE_INSTALL_DIR/bin
SPIKE_INC_DIR=$SPIKE_INSTALL_DIR/include
SPIKE_LIB_DIR=$SPIKE_INSTALL_DIR/lib

export PATH=${SPIKE_BIN_DIR}:$PATH
export LD_LIBRARY_PATH=${SPIKE_LIB_DIR}:$LD_LIBRARY_PATH
export LD_INCLUDE_PATH=${SPIKE_INC_DIR}:$LD_INCLUDE_PATH
export LIBRARY_PATH=${SPIKE_LIB_DIR}:$LIBRARY_PATH

module load riscv-toolchain/master-v20251230
